version: "3.1"

services:
  gitrub:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app:cached
    ports:
      - "4000:80"
    command: /entrypoint.sh
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
