CREATE TABLE users (
    id BIGINT PRIMARY KEY,
    login VARCHAR(39) UNIQUE NOT NULL ,
    node_id TEXT,
    avatar_url TEXT,
    gravatar_id TEXT,
    url TEXT,
    html_url TEXT,
    followers_url TEXT,
    following_url TEXT,
    gists_url TEXT,
    starred_url TEXT,
    subscriptions_url TEXT,
    organizations_url TEXT,
    repos_url TEXT,
    events_url TEXT,
    received_events_url TEXT,
    type TEXT,
    site_admin BOOL,
    created_at DATETIME DEFAULT NOW(),
    updated_at DATETIME DEFAULT NOW() ON UPDATE NOW(),
    INDEX idx_site_admin_id (site_admin, id)
) DEFAULT CHARSET=utf8mb4;
CREATE TABLE repositories (
    id BIGINT PRIMARY KEY,
    node_id TEXT,
    name VARCHAR(100),
    full_name VARCHAR(140) UNIQUE NOT NULL,
    owner_id BIGINT references users(id),
    private BOOL,
    html_url TEXT,
    description LONGTEXT,
    fork BOOL,
    url TEXT,
    archive_url TEXT,
    assignees_url TEXT,
    blobs_url TEXT,
    branches_url TEXT,
    collaborators_url TEXT,
    comments_url TEXT,
    commits_url TEXT,
    compare_url TEXT,
    contents_url TEXT,
    contributors_url TEXT,
    deployments_url TEXT,
    downloads_url TEXT,
    events_url TEXT,
    forks_url TEXT,
    git_commits_url TEXT,
    git_refs_url TEXT,
    git_tags_url TEXT,
    git_url TEXT,
    issue_comment_url TEXT,
    issues_url TEXT,
    keys_url TEXT,
    labels_url TEXT,
    languages_url TEXT,
    merges_url TEXT,
    milestones_url TEXT,
    notifications_url TEXT,
    pulls_url TEXT,
    releases_url TEXT,
    ssh_url TEXT,
    stargazers_url TEXT,
    statuses_url TEXT,
    subscribers_url TEXT,
    subscription_url TEXT,
    tags_url TEXT,
    teams_url TEXT,
    trees_url TEXT,
    hooks_url TEXT,
    created_at DATETIME DEFAULT NOW(),
    updated_at DATETIME DEFAULT NOW() ON UPDATE NOW(),
    INDEX idx_fork_id (fork, id),
    INDEX idx_owner_id_id (owner_id, id),
    INDEX idx_name_id (name, id)
) DEFAULT CHARSET=utf8mb4;

CREATE TABLE scrape_state (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  scraper_name VARCHAR(50) UNIQUE,
  last_scraped_id BIGINT NOT NULL
) DEFAULT CHARSET=utf8mb4;
