name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
      - uses: php-actions/composer@v5
        with:
          php_version: 8.0.6
          version: 2
          progress: yes
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          php_version: 8.0.6
          configuration: test/phpunit.xml
