name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: gitrub_test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
      - uses: php-actions/composer@v5
        with:
          php_version: 8.0.6
          version: 2
          progress: yes
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
          DATABASE_TEST_URI: 'mysql://root:password@mysql:${{ job.services.mysql.ports[3306] }}/gitrub_test'
        with:
          php_version: 8.0.6
          bootstrap: vendor/autoload.php
          configuration: tests/phpunit.xml
          php_extensions: pdo pdo_mysql
